### ISSUE TITLE
Restrictions on cameras being added

### ISSUE THREAD

**Issue by lbreede** [AntonPalmqvist/physically-based-api#19]
Hi,
I'd be more than happy to add more cameras to the mix, just wondering if there are any restrictions on what type of cameras to add or if it's "the more the merrier". I wouldn't be adding super obscure outdated potato cameras, but maybe some common Sony Cine Cameras and more Alpha cameras.

**Comment by AntonPalmqvist** [comment]
Hi!

Any cameras that are being used, or simulated, in any way in CG productions (including games), are welcome!
