### ISSUE TITLE
Missing crucials info on cameras

### ISSUE THREAD

**Issue by dkeraudren** [AntonPalmqvist/physically-based-api#2]
It would be great to have a more exhaustive list on sensor size for camera. For a lot of camera, the sensor size is different for each recording format, for example on the alexa mini:

S16 HD: 13.20 x 7.43 mm / 0.520 x 0.292"
HD: 23.76 x 13.37 mm / 0.935 x 0.526"
2K: 23.66 x 13.30 mm / 0.932 x 0.524"
3.2K: 26.40 x 14.85 mm / 1.039 x 0.585"
4K UHD: 26.40 x 14.85 mm / 1.039 x 0.585"
4:3 2.8K: 23.76 x 17.82 mm / 0.935 x 0.702"
2.39:1 2K Ana.: 21.12 x 17.70 mm / 0.831 x 0.697"
HD Ana.: 15.84 x 17.82 mm / 0.624 x 0.702"
ARRIRAW 16:9 2.8K: 23.76 x 13.37 mm / 0.935 x 0.526"
Open Gate 3.4K: 28.25 x 18.17 mm / 1.112 x 0.715"

Would be nice to display those information too

**Comment by AntonPalmqvist** [comment]
Hi! Thanks for the feedback!
This is one of the most requested features for the database and I'm working on an update that will include these values.

**Comment by dkeraudren** [comment]
That's very nice then, I'm pretty sure you are familiar with this website https://vfxcamdb.com/
Your website will be such an improvement for dcc tool

**Comment by AntonPalmqvist** [comment]
Yes, that's a really nice resource, and a great complement to Physically Based.
Physically Based is in many ways doing the same thing, but with a focus on always providing a source for the data, and keeping it open source.

**Comment by AntonPalmqvist** [comment]
I've now updated the cameras with sizes for the different sensor formats: https://github.com/AntonPalmqvist/physically-based-api/blob/main/deploy/cameras.json

This is how they're presented on the website:
![image](https://user-images.githubusercontent.com/13031779/185779001-a1b3e753-cc0b-401c-878b-e31460c4f319.png)
