### ISSUE TITLE
Can add these camera parameters in usd to json?

### ISSUE THREAD

**Issue by chenpaner** [AntonPalmqvist/physically-based-api#53]
{
        float2 clippingRange = (0.1, 10000)
        float focalLength = 35
        float focusDistance = 5
        token projection = "perspective"
        float horizontalAperture = 17.78
        float horizontalApertureOffset = 0
        float verticalAperture = 10.00
        float verticalApertureOffset = 0
    }
hi, I found that usd camera parameters are more detailed, But need to manually download each usd file into blender to get the correct physical camera.

**Comment by AntonPalmqvist** [comment]
Hi!

Are you saying that you want these parameters to also be present in the API?
If that's the case, everything you need is already available in API. These are just USD specific parameters that have to be there in order to create a functioning camera.

**horizontalAperture** and **verticalAperture** are the same as sensor **width** and **height** and that's all you really need to replicate a specific camera.

**Comment by chenpaner** [comment]
I mean, the other parameters,
clippingRange = （0.1， 10000）
float focalLength = 35
float focusDistance = 5
token projection = “perspective”

**Comment by AntonPalmqvist** [comment]
Those are just there for convenience to make the virtual camera function properly.
They don't have anything to do with the real camera sensor and you can change them however you want after importing.

- clippingRange controls how close and how far you can move the camera before it starts clipping the scene.
- focalLength controls the focal length of the virtual lens attached to the camera, or the "zoom" if you will
- focusDistance controls the focus of the virtual lens and affects the depth of field
- token projection tells the renderer which type of virtual lens should be used, in this case "perspective" which is the most common one. Other types are "orthographic" for example.

These will not be added to the API as they're not needed to define the look of the camera. However, I'm working on a lens database which will have parameters such as focalLength.
